In [1]:
import os
from dataset import Dataset

__ORIG_WD__ = os.getcwd()
os.chdir(f"{__ORIG_WD__}/../data_collectors")

from ncbi_genome import NCBIGenome

os.chdir(__ORIG_WD__)


2023-06-24 18:31:47.014349: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-24 18:31:47.080369: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-24 18:31:48.412691: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
dc = NCBIGenome()

In [3]:
taxa = dc.getLocalTaxa()
accession_taxa_list = []
for taxon in taxa:
    for accession in dc.getLocalAccessions(taxon):
        accession_taxa_list.append((accession, taxon))

In [4]:
dataset = Dataset(accession_taxa_list)

2023-06-24 18:31:54.447432: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-24 18:31:54.498583: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-24 18:31:54.499550: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [4]:
import os
from dataset import Dataset
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1" # Uncomment to disable GPU
import numpy as np

__ORIG_WD__ = os.getcwd()

os.chdir(f"{__ORIG_WD__}/../data_collectors/")
from covid19_genome import Covid19Genome


os.chdir(__ORIG_WD__)


2023-06-24 19:09:03.155901: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-24 19:09:03.225275: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-24 19:09:04.760917: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [5]:
covid19_genome = Covid19Genome()

lineages = covid19_genome.getLocalLineages(0)
lineages.sort()
dataset = []
for lineage in lineages[:10]:
    for accession in covid19_genome.getLocalAccessionsPath(lineage):
        dataset.append((accession, lineage))

Building Data frame
Done building Data frame
Building remote dicts
Done building remote dicts
Building local dicts
Done building local dicts


In [6]:
dataset = Dataset(dataset, minhash_dataset=True)

2023-06-24 19:09:27.304943: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-24 19:09:27.347246: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-24 19:09:27.347735: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [24]:
examples = []
labels = []
dataset.set_num_frags(1)
for example, label in dataset.get_tf_dataset(repeats=1, shuffle_buffer_size=100, batch_size=1).take(5):
    examples.append(example.numpy())
    labels.append(label.numpy())

2023-06-24 19:12:33.590748: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'args_0' with dtype string
	 [[{{node args_0}}]]
2023-06-24 19:12:33.687497: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [2432]
	 [[{{node Placeholder/_0}}]]
2023-06-24 19:12:33.688342: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_14' with dtype string and shape [2432]
	 [[{{node Placeholder/_14}}]]

In [25]:
import tensorflow as tf

meow = tf.reduce_sum(tf.cast(tf.reduce_all(examples[1] == examples[2], axis=-1), dtype=tf.int32), axis=-1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
meow

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[37]], dtype=int32)>

In [28]:
kmers = tf.random.uniform(
    shape=[30000],
    minval=0,
    maxval= 100000000,
    dtype=tf.dtypes.int64,
    seed=42
)
kmers = tf.reshape(kmers, [30000])

In [29]:
salted_kmers = tf.bitwise.bitwise_xor(
    kmers,
    tf.random.stateless_uniform([30000], minval=0, maxval=100000000, seed=[42, 42], dtype=tf.dtypes.int64)
)

In [34]:
tf.math.top_k(salted_kmers, k=128).indices

<tf.Tensor: shape=(128,), dtype=int32, numpy=
array([26676, 26330, 25697,  5382,  5808, 20275,  4553, 22097, 12359,
        8629,  6478, 17735,  3915, 13412, 26563, 24544, 26565, 25345,
       23310,  9072, 22944,  7946, 28110, 28846, 26320, 29182,  4666,
       15830, 11802,   815, 21739, 19900, 13950, 24019,  9067, 26172,
       12799, 28709, 10594, 13201, 22049, 29335, 17672, 19854,  7822,
       26718, 16240,  8095,  6057, 18787, 23065,  4742,  8214, 11647,
       20264, 14507, 25036, 25143, 27018, 19102, 14093, 27147,  2601,
        1872, 27828, 24792,  4682, 19087,  2781, 23858, 27905, 28232,
        3791, 29857, 19680, 24955,    27,  5758, 27548,  3025, 22907,
       14716, 17458, 13886, 24164, 27553, 13099,   960, 17607,  2439,
       23743, 20934, 11364, 22066, 24141,   961, 11631, 17665, 14022,
       14490, 28984, 11680, 14680,  3681,  4352, 14052, 24404,   743,
       22840,  9488, 10968,  2343, 15157,  7725,  4046, 16799, 28844,
       12777,  3381,  8580,   799,  2244, 24

In [1]:
import tensorflow as tf

2023-06-24 18:28:29.636251: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-24 18:28:29.702795: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-24 18:28:31.149564: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [7]:
tf.random.stateless_uniform([10], minval=0, maxval=10, seed=[42, 42], dtype=tf.dtypes.int64)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([9, 0, 6, 6, 8, 9, 0, 4, 6, 2])>